import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://testautomationpractice.blogspot.com/');
  await page.getByRole('textbox', { name: 'Enter Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Name' }).fill('Vraddhi');
  await page.getByRole('textbox', { name: 'Enter EMail' }).click();
  await page.getByRole('textbox', { name: 'Enter EMail' }).fill('vraddhi@test.com');
  await page.getByRole('textbox', { name: 'Enter Phone' }).click();
  await page.getByRole('textbox', { name: 'Enter Phone' }).fill('+911234567');
  await page.getByRole('textbox', { name: 'Address:' }).click();
  await page.getByRole('textbox', { name: 'Address:' }).fill('Revell Orchid');
  await page.getByRole('radio', { name: 'Female' }).check();
  await page.getByRole('checkbox', { name: 'Monday' }).check();
  await page.getByRole('checkbox', { name: 'Tuesday' }).check();
  await page.getByRole('checkbox', { name: 'Wednesday' }).check();
  await page.getByLabel('Country:').selectOption('japan');
  await page.getByLabel('Colors:').selectOption('blue');
  await page.getByLabel('Colors:').selectOption(['blue', 'green']);
  await page.getByLabel('Sorted List:').selectOption('giraffe');
  await page.getByLabel('Sorted List:').selectOption(['giraffe', 'lion']);
  await page.locator('#datepicker').click();
  await page.getByTitle('Prev').dblclick();
  await page.locator('#ui-datepicker-div').getByRole('link', { name: '1', exact: true }).click();
  await page.locator('#txtDate').click();
  await page.getByTitle('Prev').click();
  await page.getByTitle('Prev').dblclick();
  await page.locator('#ui-datepicker-div').getByRole('link', { name: '2', exact: true }).click();
  await page.getByPlaceholder('Start Date').fill('2026-05-05');
  await page.getByPlaceholder('End Date').fill('2026-05-07');
  await page.locator('#post-body-1307673142697428135').getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('cell', { name: 'Mukesh' }).nth(1).click();
  await page.locator('tr:nth-child(3) > td:nth-child(4) > input').check();
  await page.getByRole('cell').filter({ hasText: /^$/ }).nth(3).click();
  await page.locator('tr:nth-child(4) > td:nth-child(4) > input').check();
  await expect(page.locator('tr:nth-child(3) > td:nth-child(4) > input')).toBeChecked();
  await page.locator('tr:nth-child(4) > td:nth-child(4) > input').uncheck();
  await page.getByRole('textbox', { name: 'Select an item' }).click();
  await expect(page.getByText('Item 6', { exact: true })).toBeVisible();
  await page.locator('.ui-slider-handle').first().click();
  await page.locator('.ui-slider-range').click();
  await page.locator('.ui-slider-handle.ui-corner-all.ui-state-default.ui-state-hover').click();
});